export default {
  GET_ALBUMS_LIST_REQUEST: "GET_ALBUMS_LIST_REQUEST",
  GET_ALBUMS_LIST_RESPONSE: "GET_ALBUMS_LIST_RESPONSE",

  GET_ALBUMS_BY_ID_REQUEST: "GET_ALBUMS_BY_ID_REQUEST",
  GET_ALBUMS_BY_ID_RESPONSE: "GET_ALBUMS_BY_ID_RESPONSE",
  GET_ALBUMS_BY_ID_RESPONSE_CLEAR: "GET_ALBUMS_BY_ID_RESPONSE_CLEAR",

  POST_ALBUMS_REQUEST: "POST_ALBUMS_REQUEST",
  POST_ALBUMS_RESPONSE: "POST_ALBUMS_RESPONSE",
  POST_ALBUMS_RESPONSE_CLEAR: "POST_ALBUMS_RESPONSE_CLEAR",

  PUT_ALBUMS_REQUEST: "PUT_ALBUMS_REQUEST",
  PUT_ALBUMS_RESPONSE: "PUT_ALBUMS_RESPONSE",
  PUT_ALBUMS_RESPONSE_CLEAR: "PUT_ALBUMS_RESPONSE_CLEAR",

  DELETE_ALBUMS_REQUEST: "DELETE_ALBUMS_REQUEST",
  DELETE_ALBUMS_RESPONSE: "DELETE_ALBUMS_RESPONSE",
  DELETE_ALBUMS_RESPONSE_CLEAR: "DELETE_ALBUMS_RESPONSE_CLEAR",
};
