export default {
  GET_PHOTOSALBUM_MAPPING_LIST_REQUEST: "GET_PHOTOSALBUM_MAPPING_LIST_REQUEST",
  GET_PHOTOSALBUM_MAPPING_LIST_RESPONSE:
    "GET_PHOTOSALBUM_MAPPING_LIST_RESPONSE",

  GET_PHOTOSALBUM_MAPPING_BY_ID_REQUEST:
    "GET_PHOTOSALBUM_MAPPING_BY_ID_REQUEST",
  GET_PHOTOSALBUM_MAPPING_BY_ID_RESPONSE:
    "GET_PHOTOSALBUM_MAPPING_BY_ID_RESPONSE",
  GET_PHOTOSALBUM_MAPPING_BY_ID_RESPONSE_CLEAR:
    "GET_PHOTOSALBUM_MAPPING_BY_ID_RESPONSE_CLEAR",

  POST_PHOTOSALBUM_MAPPING_REQUEST: "POST_PHOTOSALBUM_MAPPING_REQUEST",
  POST_PHOTOSALBUM_MAPPING_RESPONSE: "POST_PHOTOSALBUM_MAPPING_RESPONSE",
  POST_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR:
    "POST_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR",

  PUT_PHOTOSALBUM_MAPPING_REQUEST: "PUT_PHOTOSALBUM_MAPPING_REQUEST",
  PUT_PHOTOSALBUM_MAPPING_RESPONSE: "PUT_PHOTOSALBUM_MAPPING_RESPONSE",
  PUT_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR:
    "PUT_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR",

  DELETE_PHOTOSALBUM_MAPPING_REQUEST: "DELETE_PHOTOSALBUM_MAPPING_REQUEST",
  DELETE_PHOTOSALBUM_MAPPING_RESPONSE: "DELETE_PHOTOSALBUM_MAPPING_RESPONSE",
  DELETE_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR:
    "DELETE_PHOTOSALBUM_MAPPING_RESPONSE_CLEAR",
};
