export default {
  GET_SEARCH_LIST_REQUEST: "GET_SEARCH_LIST_REQUEST",
  GET_SEARCH_LIST_RESPONSE: "GET_SEARCH_LIST_RESPONSE",

  POST_SEARCH_REQUEST: "POST_SEARCH_REQUEST",
  POST_SEARCH_RESPONSE: "POST_SEARCH_RESPONSE",
  POST_SEARCH_RESPONSE_CLEAR: "POST_SEARCH_RESPONSE_CLEAR",
};
