export default {
  GET_PHOTOS_LIST_REQUEST: "GET_PHOTOS_LIST_REQUEST",
  GET_PHOTOS_LIST_RESPONSE: "GET_PHOTOS_LIST_RESPONSE",

  GET_PHOTOS_BY_ID_REQUEST: "GET_PHOTOS_BY_ID_REQUEST",
  GET_PHOTOS_BY_ID_RESPONSE: "GET_PHOTOS_BY_ID_RESPONSE",
  GET_PHOTOS_BY_ID_RESPONSE_CLEAR: "GET_PHOTOS_BY_ID_RESPONSE_CLEAR",

  POST_PHOTOS_REQUEST: "POST_PHOTOS_REQUEST",
  POST_PHOTOS_RESPONSE: "POST_PHOTOS_RESPONSE",
  POST_PHOTOS_RESPONSE_CLEAR: "POST_PHOTOS_RESPONSE_CLEAR",

  PUT_PHOTOS_REQUEST: "PUT_PHOTOS_REQUEST",
  PUT_PHOTOS_RESPONSE: "PUT_PHOTOS_RESPONSE",
  PUT_PHOTOS_RESPONSE_CLEAR: "PUT_PHOTOS_RESPONSE_CLEAR",

  DELETE_PHOTOS_REQUEST: "DELETE_PHOTOS_REQUEST",
  DELETE_PHOTOS_RESPONSE: "DELETE_PHOTOS_RESPONSE",
  DELETE_PHOTOS_RESPONSE_CLEAR: "DELETE_PHOTOS_RESPONSE_CLEAR",
};
